apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}-config
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  loki.yaml: |
    auth_enabled: {{ .Values.config.auth_enabled }}

    server:
      http_listen_port: {{ .Values.config.server.http_listen_port }}

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: {{ .Values.config.ingester.lifecycler.ring.kvstore.store }}
          replication_factor: {{ .Values.config.ingester.lifecycler.ring.replication_factor }}
      chunk_idle_period: {{ .Values.config.ingester.chunk_idle_period }}
      max_transfer_retries: {{ .Values.config.ingester.max_transfer_retries }}

    schema_config:
      configs:
        {{- toYaml .Values.config.schema_config.configs | nindent 8 }}

    storage_config:
      boltdb_shipper:
        active_index_directory: {{ .Values.config.storage_config.boltdb_shipper.active_index_directory }}
        cache_location: {{ .Values.config.storage_config.boltdb_shipper.cache_location }}
        shared_store: {{ .Values.config.storage_config.boltdb_shipper.shared_store }}
      filesystem:
        directory: {{ .Values.config.storage_config.filesystem.directory }}

    limits_config:
      enforce_metric_name: {{ .Values.config.limits_config.enforce_metric_name }}
      reject_old_samples: {{ .Values.config.limits_config.reject_old_samples }}
      reject_old_samples_max_age: {{ .Values.config.limits_config.reject_old_samples_max_age }}
