{{- if .Values.global.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "loki.fullname" . }}-storage
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.global.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.global.persistence.size }}
  {{- if .Values.global.persistence.storageClassName }}
  storageClassName: {{ .Values.global.persistence.storageClassName }}
  {{- end }}
{{- end }}
