loki:
  schemaConfig:
    configs:
      - from: 2024-06-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    max_concurrent: 4

deploymentMode: SimpleScalable

backend:
  replicas: 3

read:
  replicas: 3

write:
  replicas: 3

minio:
  enabled: true

singleBinary:
  replicas: 0

ingester:
  replicas: 1

querier:
  replicas: 1

queryFrontend:
  replicas: 1

queryScheduler:
  replicas: 0

distributor:
  replicas: 1

compactor:
  replicas: 0

indexGateway:
  replicas: 0

bloomCompactor:
  replicas: 0

bloomGateway:
  replicas: 0

ingress:
  enabled: true
  host: loki.cloudmasa.com
  # TLS configuration
  tls:
    enabled: true
    secretName: loki-tls-secret # Name of the Kubernetes secret containing the SSL certificate (CRT)
    certManager: true  # Use cert-manager if available (can be set to false if not needed)

# Set to true if you are using cert-manager for automatic certificate management
certManager
