loki:
  schemaConfig:
    configs:
      - from: 2024-06-01
        store: tsdb
        object_store: filesystem  # Use 'filesystem' for local storage
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  ingester:
    chunk_encoding: snappy

  tracing:
    enabled: true

  querier:
    max_concurrent: 4

  # Removed alertmanager_config and queryrange configurations that were causing issues

deploymentMode: SimpleScalable

backend:
  replicas: 3

read:
  replicas: 3

write:
  replicas: 3

minio:
  enabled: false  # No need for Minio if you're using filesystem storage

singleBinary:
  replicas: 0

ingester:
  replicas: 1

querier:
  replicas: 1

queryFrontend:
  replicas: 1

queryScheduler:
  replicas: 0

distributor:
  replicas: 1

compactor:
  replicas: 0

indexGateway:
  replicas: 0

bloomCompactor:
  replicas: 0

bloomGateway:
  replicas: 0

ingress:
  enabled: true
  host: loki.cloudmasa.com
