loki:
  auth_enabled: false

  server:
    http_listen_port: 3100

  distributor:
    ring:
      kvstore:
        store: memberlist

  ingester:
    lifecycler:
      ring:
        kvstore:
          store: memberlist
        replication_factor: 1
      final_sleep: 0s
    chunk_encoding: snappy
    chunk_idle_period: 5m
    max_chunk_age: 1h
    chunk_target_size: 1048576
    chunk_retain_period: 30s

  schema_config:
    configs:
      - from: 2024-06-01
        store: tsdb
        object_store: filesystem
        schema: v12  # Corrected from v13 to v12
        index:
          prefix: loki_index_
          period: 24h

  storage_config:
    filesystem:
      directory: /data/loki

  compactor:
    working_directory: /data/compactor
    shared_store: filesystem

  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h

  chunk_store_config:
    max_look_back_period: 0s

  table_manager:
    retention_deletes_enabled: true
    retention_period: 168h

  tracing:
    enabled: true

  querier:
    max_concurrent: 4

deploymentMode: SimpleScalable

backend:
  replicas: 3

read:
  replicas: 3

write:
  replicas: 3

minio:
  enabled: false

singleBinary:
  replicas: 0

ingester:
  replicas: 1

querier:
  replicas: 1

queryFrontend:
  replicas: 1

distributor:
  replicas: 1

compactor:
  replicas: 0

indexGateway:
  replicas: 0

bloomCompactor:
  replicas: 0

bloomGateway:
  replicas: 0

ingress:
  enabled: true
  host: loki.cloudmasa.com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  ingressClassName: "nginx"

persistence:
  enabled: true
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"
