loki:
  schemaConfig:
    configs:
      - from: 2024-06-01
        store: tsdb
        object_store: filesystem  # Using filesystem for local storage
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  ingester:
    chunk_encoding: snappy
    replicas: 1  # Set the number of ingesters

  tracing:
    enabled: true

  querier:
    max_concurrent: 4

  distributor:
    replicas: 1  # Number of distributor replicas
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"

  compactor:
    replicas: 0  # Set compactor replicas to 0 if you don't need it

  indexGateway:
    replicas: 0  # Set indexGateway replicas to 0 if you don't need it

  bloomCompactor:
    replicas: 0  # Set bloomCompactor replicas to 0 if you don't need it

  bloomGateway:
    replicas: 0  # Set bloomGateway replicas to 0 if you don't need it

  minio:
    enabled: false  # Minio is disabled since we are using filesystem for storage

  read:
    replicas: 3

  write:
    replicas: 3

  backend:
    replicas: 3  # Number of backend replicas

  singleBinary:
    replicas: 0  # No single binary deployment

  ingress:
    enabled: true
    host: loki.cloudmasa.com  # Update this with your actual hostname
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"  # In case you need to rewrite URL paths
      nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable SSL redirect if not using HTTPS
    ingressClassName: "nginx"  # Make sure the ingress controller class matches your setup

  storageConfig:
    filesystem:
      directory: /loki/chunks  # Ensure Loki stores its chunks in the filesystem
    boltdb_shipper:
      active_index_directory: /loki/index  # Index storage path
      cache_location: /loki/cache  # Cache storage path
      cache_ttl: 1h  # TTL for the cache

  persistence:
    enabled: true
    storageClassName: "gp3-csi"  # Adjust to your cluster's storage class (if applicable)
    accessMode: ReadWriteOnce
    size: 50Gi  # Adjust the size based on your needs

  # Enable Loki's various components
  components:
    - distributor
    - ingester
    - querier
    - queryFrontend
    - compactor

# Disable unneeded components
disableCompactor: true
disableIndexGateway: true
disableBloomCompactor: true
disableBloomGateway: true
