loki:
  schemaConfig:
    configs:
      - from: 2024-06-01
        store: tsdb
        object_store: filesystem  # Using filesystem for local storage
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  ingester:
    chunk_encoding: snappy  # Set chunk encoding to snappy

  tracing:
    enabled: true  # Enable tracing for Loki

  querier:
    max_concurrent: 4  # Max concurrent queries

deploymentMode: SimpleScalable  # Set deployment mode for scalable Loki setup

# Number of replicas for different components in the Loki deployment
backend:
  replicas: 3  # Replicas for backend components

read:
  replicas: 3  # Replicas for read components

write:
  replicas: 3  # Replicas for write components

minio:
  enabled: false  # Disable Minio, not needed with local storage

singleBinary:
  replicas: 0  # No need for singleBinary in this case

ingester:
  replicas: 1  # Number of ingester replicas

querier:
  replicas: 1  # Number of querier replicas

queryFrontend:
  replicas: 1  # Number of queryFrontend replicas

distributor:
  replicas: 1  # Number of distributor replicas

compactor:
  replicas: 0  # No need for compactor unless scaling

indexGateway:
  replicas: 0  # No need for indexGateway unless scaling

bloomCompactor:
  replicas: 0  # No need for bloomCompactor unless scaling

bloomGateway:
  replicas: 0  # No need for bloomGateway unless scaling

ingress:
  enabled: true  # Set to true to enable ingress
  host: loki.cloudmasa.com  # Set your actual hostname here
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable SSL redirect if not using SSL
  ingressClassName: "nginx"  # Set ingress class if you're using NGINX Ingress controller
  # Add additional ingress configurations as needed

# Add persistent storage configuration if you're using persistent volumes
persistence:
  enabled: true  # Enable persistence
  storageClassName: "gp3"  # Set the appropriate storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Set storage size (adjust as needed)

# Optional: For monitoring or alerts (if applicable)
alertmanager:
  enabled: false  # Disable Alertmanager if not using
