loki:
  enabled: true
  config: 
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    schema_config:
      configs:
        - from: 2024-06-01
          store: tsdb
          object_store: filesystem
          schema: v12
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      filesystem:
        directory: /data/loki

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h

    querier:
      max_concurrent: 20

  storage:
    type: filesystem
    filesystem:
      directory: /data/loki

persistence:
  enabled: true
  storageClassName: gp3-csi  # change as per your cluster
  accessModes:
    - ReadWriteOnce
  size: 10Gi

volumeMounts:
  - name: storage
    mountPath: /data/loki

volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: loki-pvc

resources: 
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 100m
