apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  loki.yaml: |
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info

    querier:
      query_timeout: 1m
      max_query_parallelism: 32
      query_ingester_streams: true

    distributor:
      ring:
        kvstore:
          store: inmemory

    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/cache
        resync_interval: 1m
      filesystem:
        directory: /data/loki/chunks

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h
