apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}-config
  labels:
    app: {{ include "loki.fullname" . }}
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 3m
      max_chunk_age: 1h
      chunk_block_size: 262144
      chunk_encoding: snappy
      wal:
        enabled: false

    schema_config:
      configs:
        - from: 2024-06-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      filesystem:
        directory: /data/loki/chunks

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
