apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "loki.fullname" . }}-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/{{ include \"loki.fullname\" . }}"
