apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "loki.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual  # Match the storage class here
